spring.application.name=antaracares

# Database Configurations
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:antaracaresdb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Java Mail Configurations
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER:dineshjustin95@gmail.com}
spring.mail.password=${SMTP_PASSWORD:pptdclqpbfiemtbp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Production Configurations
security.allowed-origin=${ALLOWED_ORIGIN:http://localhost:5173}

# Spring Data REST Properties
spring.data.rest.base-path=/api
spring.data.rest.default-page-size=20

logging.level.org.springframework.security=DEBUG